[pytest]
testpaths = tests
python_files = test_*.py
addopts = -vv --capture=no --html=report.html --self-contained-html
log_cli = true
log_cli_level = INFO
markers =
    smoke: Basic sanity checks for SauceDemo.
    regression: Regression tests for the SauceDemo application.
    ui: UI-focused browser tests.
